<?php
/**
 * Author: dungang
 * Date: 2017/6/21
 * Time: 22:17
 */

namespace dungang\activity\workflow\controllers;


use yii\web\Controller;

class BaseController extends Controller
{

    public function render($view, $params = [])
    {
        if (\Yii::$app->request->isAjax)
            return parent::renderAjax($view,$params);
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}